about/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.about_me, name='about'),
]

booking/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('our-services/', views.ServiceList.as_view(), name='services'),
    path('my-appointments/', views.my_appointments, name='appointments'),
    path('edit_appointment/<int:appointment_id>/', views.appointment_edit, name='appointment_edit'),
    path('delete_appointment/<int:appointment_id>/', views.appointment_delete, name='appointment_delete'),
]

bravos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path("booking/", include("booking.urls"), name="booking-urls"),
    path('summernote/', include('django_summernote.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),

]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from about.models import JobStatus, Stylist


class Service(models.Model):
    """
    Model to store information about services provided by the barber shop.
    
    **Fields**

        popular (IntegerField): The popularity score of the service.
        title (CharField): The title of the service.
        price (DecimalField): The price of the service.
        level (ForeignKey): The qualification level required for the service, linked to the JobStatus model.

    """

    popular = models.IntegerField()
    title = models.CharField(max_length=200, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    level = models.ForeignKey(
        JobStatus, on_delete=models.CASCADE, to_field='qualif_level'
    )

    class Meta:
        ordering = ['popular']

    def __str__(self):
        return self.title


class AppointmentTime(models.Model):
    """
    Model to store appointment times.
    
    **Fields**
    
        title (TimeField): The time of the appointment.

    """
    title = models.TimeField(unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title.strftime('%H:%M')


class Appointment(models.Model):
    """
    Model to store information about appointments.
    
    **Fields**
    
        author (ForeignKey): The user who made the appointment, linked to the User model.
        title (ForeignKey): The type of service for the appointment, linked to the Service model.
        stylist (ForeignKey): The stylist assigned to the appointment, linked to the Stylist model.
        date_appo (DateField): The date of the appointment.
        time_appo (ForeignKey): The time of the appointment, linked to the AppointmentTime model.

    """

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="client"
    )
    title = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name='servicetype'
    )
    stylist = models.ForeignKey(
        Stylist, on_delete= models.CASCADE, to_field='stylist_id'
    )
    date_appo = models.DateField()
    time_appo = models.ForeignKey(
        AppointmentTime, on_delete=models.CASCADE, related_name='appointmenttime'
    )

    class Meta:
        ordering = ['date_appo', 'time_appo']

    def __str__(self):
        return f"{self.title} for {self.author} with {self.stylist} on {self.date_appo} at {self.time_appo}"

booking/forms.py
from .models import Appointment
from django import forms


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('title', 'stylist', 'date_appo', 'time_appo')
        widgets = {
            'date_appo': forms.DateInput(attrs={'class': 'form-control datepicker'})
        }
        labels = {
            'title': 'Service',
            'stylist': 'Stylist',
            'date_appo': 'Appointment Date',
            'time_appo': 'Appointment Time',
        }
        for field_name in fields:
            field = {field_name: forms.CharField(required=True)}

booking/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import AppointmentForm
from .models import Service, Appointment


# Service list view to display the service's the barber provides
class ServiceList(LoginRequiredMixin, generic.ListView):
    """
    Display the list of services provided by the barber.
    
    Requires login.

    **Context**

    ``queryset``
        Queryset of all services ordered by popularity.
    
    **Template:**

    :template:`booking/services.html`

    """
    queryset = Service.objects.all().order_by('popular')
    template_name = "booking/services.html"


# CREATE + READ: Appointment view for creation and read of appointments
@login_required
def my_appointments(request):
    """
    Renders the 'My Appointments' page.
    
    Allows users to view their appointments and create new appointments.

    Requires login.

    **Context**

    ``appointments``
        Queryset of appointments belonging to the current user.
    ``appointment_form``
        Form object for creating new appointments.

    **Template:**

    :template:`booking/my-appointments.html`

    """
    if request.method == "POST":
        appointment_form = AppointmentForm(data=request.POST)
        if appointment_form.is_valid():
            appointment = appointment_form.save(commit=False)
            appointment.author = request.user
            appointment.save()
            messages.success(request, "You have made your appointment! We look forward to seeing you.")
            return redirect("appointments")

    appointments = Appointment.objects.filter(author=request.user).order_by('date_appo')
    appointment_form = AppointmentForm()

    return render(
        request,
        "booking/my-appointments.html",
        {
            "appointments": appointments,
            "appointment_form": appointment_form
        },
    )


# UPDATE: Appointment view for editing of appointments
@login_required
def appointment_edit(request, appointment_id):
    """
    Edit an appointment.

    Requires login.

    **Context**

    ``appointment``
        The appointment instance to be edited.
    ``appointment_form``
        Form object for editing the appointment.

    """
    if request.method == "POST":

        appointment = get_object_or_404(Appointment, pk=appointment_id)
        appointment_form = AppointmentForm(data=request.POST, instance=appointment)
        
        if appointment_form.is_valid() and appointment.author == request.user:
            appointment = appointment_form.save(commit=False)
            appointment.save()
            messages.add_message(request, messages.SUCCESS, 'Appointment Updated!')
        else:
                messages.add_message(request, messages.ERROR, 'Error updating appointment')
        
    return HttpResponseRedirect(reverse('appointments'))


# DELETE: Appointment view for deletion of appointments
@login_required
def appointment_delete(request, appointment_id):
    """
    Delete an appointment.

    Requires login.

    **Context**

    ``appointment``
        The appointment instance to be deleted.

    """
    appointment = get_object_or_404(Appointment, pk=appointment_id)

    if appointment.author == request.user:
        appointment.delete()
        messages.add_message(request, messages.SUCCESS, 'Appointment deleted!')
    else:
        messages.add_message(request, messages.ERROR,'You can only delete your own appointments!')

    return HttpResponseRedirect(reverse('appointments'))

booking/templates/booking/my-appointments.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Make Appointments Masthead -->
<header class="masthead" id="update">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center">
                <h1 class="mx-auto my-0 text-uppercase">Make Appointment</h1>
                <h2 class="text-white-50 mx-auto mt-2 mb-5">Make appointments here! And find all you're upcoming
                    appointments below..</h2>
                <div class="card bg-light">
                    <div class="card-body">
                        <form id="appointmentForm" class="text-center" method="post">
                            {{ appointment_form | crispy }}
                            {% csrf_token %}
                            <div class="text-center">
                                <button id="submitButton" class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- My Appointments Section -->
<section class="projects-section my-5" id="projects">
    <h2 class="mx-auto my-0 text-uppercase text-center">My Appointments</h2>
    <p class="text-black-50 text-center py-2 px-5">Access a comprehensive list of all your appointments, displaying
        every booking you've made for easy reference.</p>
    <div class="container px-5 px-lg-6">
        <!-- Displaying users appointments Rows -->
        <div class="row">
            {% if appointments|length > 0 %}
            {% for appointment in appointments %}
            {% if appointment.author == request.user %}
            <div class="col-lg-4 mb-4">
                <div class="card h-100 bg-light">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <div id="appointment{{ appointment.id }}" class="appointment-details">
                            <div class="row">
                                <h4 id='id_title' class="card-title service-title">{{ appointment.title }}</h4>
                                <h5 class="card-title text-black-50">{{ appointment.title.price }}</h5>
                            </div>
                            <hr>
                            <ul>
                                <li id='id_stylist' class="card-text stylist">Stylist:
                                    <strong>{{ appointment.stylist }}</strong></li>
                                <li id='id_date_appo' class="card-text date">When:
                                    <strong>{{ appointment.date_appo }}</strong></li>
                                <li id='id_time_appo' class="card-text time">Time:
                                    <strong>{{ appointment.time_appo }}</strong></li>
                            </ul>
                        </div>
                        <div>
                            <hr>
                            <div class="row justify-content-center">
                                <button class="col-5 btn btn-primary text-uppercase mx-2 btn-edit edit-btn"
                                    data-appointment_id="{{ appointment.id }}"
                                    onclick="scrollToSection('update')">Edit</button>
                                <button class="col-5 btn btn-primary text-uppercase mx-2 btn-delete delete-btn"
                                    data-appointment_id="{{ appointment.id }}">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="col-12">
                <h5 class="text-black-50 text-center py-2 px-5">It appears that you haven't made any appointments
                    yet.<br>
                    To schedule one, please utilize the <a class="btn-primary"
                        onclick="scrollToSection('update')">form</a> provided above.
                </h5>
            </div>
            {% endif %}
        </div>
</section>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Appointment?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your appointment? This action cannot be undone.
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn edit-btn" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn delete-btn">Delete</a>
            </div>
        </div>
    </div>
</div>

<!-- function for datepicker for date_appo -->
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true
        });
    });
</script>

<script src="{% static 'js/appointments.js' %}"></script>

{% endblock content %}

booking/templates/booking/services.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Our Services Masthead -->
<header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center">
                <h1 class="mx-auto my-0 text-uppercase">Our Services</h1>
                <h2 class="text-white-50 mx-auto mt-2 mb-5"><em>"Revitalize your style with precision and passion in
                        every
                        cut at our establishment."</em></h2>
                <a class="btn btn-primary"
                    href="{% if user.is_authenticated %}{% url 'appointments' %}{% else %}{% url 'account_signup' %}{% endif %}">Make
                    an Appointment
                </a>
            </div>
        </div>
    </div>
</header>

<!-- Our Services Section -->
<section class="projects-section" id="projects">
    <h2 class="mx-auto my-0 text-uppercase text-center">Services Overview</h2>
    <p class="text-black-50 text-center py-2 px-5">Explore our range of services, from classic and modern cuts to an
        Italian shave. All treatments and prices are listed below.</p>
    <div class="container px-5 px-lg-6">
        <!-- Service Rows -->
        {% for service in service_list %}
        <div class="row align-items-center py-3 {% cycle 'bg-light' 'bg-white' %}">
            <div class="col-8">
                <h4 class="mb-0">{{ service.title }}</h4>
            </div>
            <div class="col-4 text-end">
                <h4 class="mb-0"><strong>{{ service.price }}</strong></h4>
            </div>
        </div>
        {% endfor %}
        <a class="btn btn-primary w-100 my-4"
            href="{% if user.is_authenticated %}{% url 'appointments' %}{% else %}{% url 'account_signup' %}{% endif %}">Schedule
            an Appointment</a>
    </div>
</section>

{% endblock content %}